<footer>
    <div class="container">
        <div class="row">
            <div class="copy-right">
                &copy; 2017 by <a href="">5Pharma</a>
            </div>
        </div>
    </div>
</footer>

<!-- main js process -->
{!! HTML::script('js/main.js') !!}

<script>
    function formatNumber (num) {
        return num.toString().replace(/(\d)(?=(\d{3})+(?!\d))/g, "$1,")
    }

    // show - hide qty box
    jQuery('.btn-cart').click(function(){
        var type_price = $(this).attr('data-type');
        jQuery('.'+type_price+'.qty-'+jQuery(this).attr('data-drug')).show();
        jQuery('.btn-cart-'+jQuery(this).attr('data-drug')).hide();
    });

    //    // load when exist old qty
    //    jQuery('.qty-count').each(function(index, elem) {
    //        if ($(elem).text() != '0') {
    //            jQuery('.qty-'+$(elem).attr('data-drug')).show();
    //            jQuery('.btn-cart-'+$(elem).attr('data-drug')).hide();
    //
    //            // set value of qty
    //            jQuery('.qty-count-'+$(elem).attr('data-drug')).val(parseInt($(elem).text()));
    //        }
    //    });

    // This button will increment the value
    $('.qty-add').click(function(e){
        // Stop acting like a button
        e.preventDefault();
        // Get the field name
        fieldName = $(this).attr('data-drug');

        // Get its current value
        var currentVal = parseInt($('.qty-count-'+fieldName).val());
        // If is not undefined
        if (!isNaN(currentVal) || $('.qty-count-'+fieldName).val() == 0) {
            if ( $('.qty-count-'+fieldName).val() == 0) {
                currentVal = 0;
            }

            // ajax add qty
            var qty_post = currentVal + 1;
            var token = $('input[name="_token"]').val();
            var mind_id = $('input[name="mind_id"]').val();
            var user_id = $('input[name="user_id"]').val();
            var price = $('.price' +fieldName).val();
            var special_price = $('.special_price' +fieldName).val();
            var  dataType = $(this).attr('data-type');
            $.ajax({
                url: '{{ url('postProductCart') }}',
                type: 'PUT',
                data: "type_add=" + dataType + "&product_id=" + fieldName + "&qty=" + qty_post + "&mind_id=" + mind_id + "&user_id=" + user_id + "&price=" + price + "&special_price=" + special_price + "&_token=" + token
            })
                .done(function(response) {
                    if(response.isRootPrice != '1' && response.isAddRoot == '0') {
                        // Increment
                        $('.type_discount_price.qty-count-'+fieldName).val(currentVal + 1);
                        $('.type_discount_price.qty-count-'+fieldName).html(currentVal + 1);
                        $('.type_discount_price.qty-minus').val("-").removeAttr('style');

                        $('.type_root_price.qty-'+fieldName).hide();

                    } else if (response.isRootPrice == '1' && response.isAddRoot == '0') {
                        // qty > qty max discount
                        $('.type_discount_price.qty-count-'+fieldName).val(currentVal);
                        $('.type_discount_price.qty-count-'+fieldName).html(currentVal);
                        $('.type_discount_price.qty-minus').val("-").removeAttr('style');

                        //$('.type_discount_price.qty-'+fieldName).show();

                        $('.type_root_price.qty-'+fieldName).show();
                    } else if(response.isRootPrice == '1' && response.isAddRoot == '1') {
                        // qty > qty max discount and is add root true
                        $('.type_root_price.qty-count-'+fieldName).val(response.cartData.qtyRoot);
                        $('.type_root_price.qty-count-'+fieldName).html(response.cartData.qtyRoot);
                        $('.type_root_price.qty-minus').val("-").removeAttr('style');

//                    $('.qty-count-'+fieldName).val(response.cartData.qtyRoot);
//                    $('.qty-count-'+fieldName).html(response.cartData.qtyRoot);

                        //$('.type_discount_price.qty-'+fieldName).show();

                        $('.type_root_price.qty-'+fieldName).show();
                    }
                    console.log(response);
                    $('.current-price').text(formatNumber(response.cartData.count_price));
                    $('.discount-price').text(formatNumber(response.cartData.count_discount));
                    //console.log(response);
                })
                .fail(function() {
                    console.log('Lỗi mua sản phẩm');
                });

        } else {
            // Otherwise put a 0 there
            $('.qty-count-'+fieldName).val(0);
            $('.qty-count-'+fieldName).html(0);

            $('.qty-'+$(this).attr('data-drug')).hide();
            $('.btn-cart-'+$(this).attr('data-drug')).show();

        }
    });
    // This button will decrement the value till 0
    $(".qty-minus").click(function(e) {
        // Stop acting like a button
        e.preventDefault();
        // Get the field name
        fieldName = $(this).attr('data-drug');
        // Get its current value
        var currentVal = parseInt($('.qty-count-'+fieldName).val());
        // If it isn't undefined or its greater than 0
        if (!isNaN(currentVal) && currentVal > 1) {

            // ajax minus qty
            var qty_post = currentVal - 1;
            var token = $('input[name="_token"]').val();
            var mind_id = $('input[name="mind_id"]').val();
            var user_id = $('input[name="user_id"]').val();
            var price = $('.price' +fieldName).val();
            var special_price = $('.special_price' +fieldName).val();
            $.ajax({
                url: '{{ url('postProductCart') }}',
                type: 'PUT',
                data: "product_id=" + fieldName + "&qty=" + qty_post + "&mind_id=" + mind_id + "&user_id=" + user_id + "&price=" + price + "&special_price=" + special_price + "&_token=" + token
            })
                .done(function(response) {
                    $('.current-price').text(formatNumber(response.cartData.count_price));
                    $('.discount-price').text(formatNumber(response.cartData.count_discount));
                    //console.log(response);
                })
                .fail(function() {
                    console.log('Lỗi mua sản phẩm');
                });

            // Decrement one
            $('.qty-count-'+fieldName).val(currentVal - 1);
            $('.qty-count-'+fieldName).html(currentVal - 1);
        } else {

            // delete product from cart when to - 0

            // Otherwise put a 0 there
            $('.qty-count-'+fieldName).val(0);
            $('.qty-count-'+fieldName).html(0);

            $('.qty-'+$(this).attr('data-drug')).hide();
            $('.btn-cart-'+$(this).attr('data-drug')).show();
        }
    });
</script>